export const VoiceEvents = {

 WAKE_DETECTED: "WAKE_DETECTED",

 VOICE_PARTIAL: "VOICE_PARTIAL",
 VOICE_TEXT: "VOICE_TEXT",

 INTENT_DETECTED: "INTENT_DETECTED",

 AI_TOKEN: "AI_TOKEN",

 SPEECH_CHUNK: "SPEECH_CHUNK",

 SPEECH_START: "SPEECH_START",
 SPEECH_END: "SPEECH_END",

 INTERRUPT: "INTERRUPT",

 ERROR: "ERROR"

} as const
